I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 777, in script call
    call foret_2 pass (lieu = "nord")
  File "game/script.rpy", line 800, in script
    label attaque_massacre_einar_sauf_foret_2(message):
Exception: Required parameter message has no value.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 777, in script call
    call foret_2 pass (lieu = "nord")
  File "game/script.rpy", line 800, in script
    label attaque_massacre_einar_sauf_foret_2(message):
  File "D:\Bibliothèque\Downloads\renpy-6.99.10-sdk\renpy\ast.py", line 752, in execute
    values = apply_arguments(self.parameters, renpy.store._args, renpy.store._kwargs)
  File "D:\Bibliothèque\Downloads\renpy-6.99.10-sdk\renpy\ast.py", line 149, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "D:\Bibliothèque\Downloads\renpy-6.99.10-sdk\renpy\ast.py", line 118, in apply
    raise Exception("Required parameter %s has no value." % name)
Exception: Required parameter message has no value.

Windows-8-6.2.9200
Ren'Py 6.99.10.1227
Harald's Dusk 0.0
