I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 701, in script call
    call choix_retour_village_1 pass (massacre = True)
  File "game/script.rpy", line 915, in script call
    call massacre_foret_2 pass (lieu = "chateau")
  File "game/script.rpy", line 1131, in script call
    call attaque_massacre_foret_2 pass (message = "deception")
  File "game/script.rpy", line 1223, in script call
    call e_demande_nom_foret_2 pass (bad_ending = true)
  File "game/script.rpy", line 1230, in script
    label e_demande_nom_foret_2(bad_ending = False):
  File "game/script.rpy", line 1223, in <module>
    call e_demande_nom_foret_2 pass (bad_ending = true)
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 701, in script call
    call choix_retour_village_1 pass (massacre = True)
  File "game/script.rpy", line 915, in script call
    call massacre_foret_2 pass (lieu = "chateau")
  File "game/script.rpy", line 1131, in script call
    call attaque_massacre_foret_2 pass (message = "deception")
  File "game/script.rpy", line 1223, in script call
    call e_demande_nom_foret_2 pass (bad_ending = true)
  File "game/script.rpy", line 1230, in script
    label e_demande_nom_foret_2(bad_ending = False):
  File "D:\Bibliothèque\Downloads\renpy-6.99.10-sdk\renpy\ast.py", line 1319, in execute
    args, kwargs = self.arguments.evaluate()
  File "D:\Bibliothèque\Downloads\renpy-6.99.10-sdk\renpy\ast.py", line 179, in evaluate
    kwargs[k] = renpy.python.py_eval(v, locals=scope)
  File "D:\Bibliothèque\Downloads\renpy-6.99.10-sdk\renpy\python.py", line 1606, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Bibliothèque\Downloads\renpy-6.99.10-sdk\renpy\python.py", line 1601, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1223, in <module>
    call e_demande_nom_foret_2 pass (bad_ending = true)
NameError: name 'true' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.10.1227
Harald's Dusk 0.0
